services:
    vistiyos_erperp.menu.voter.request:
        class: Vistiyos\ERP\ERPBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
#    vistiyos_erperp.example:
#        class: Vistiyos\ERP\ERPBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
