vistiyos_uiui:
    resource: "@VistiyosUIUIBundle/Resources/config/routing.yml"
    prefix:   /

vistiyos_crmcrm:
    resource: "@VistiyosCRMCRMBundle/Resources/config/routing.yml"
    prefix:   /

vistiyos_erperp:
    resource: "@VistiyosERPERPBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
